---
title: "Trabalho Extração"
author: "Joana Gonçalves, Bruno Sá, Gonçalo Cardoso, Luís Ferreira"
date: "`r Sys.Date()`"
output: html_document
---

# 1 - Packages

```{r}

```

# 2.1 - Import dos Dados Clinical
```{r}

clinical_clinical = read.delim("~/Documentos/GitHub/Extra-o_Work/clinical.project-TCGA-GBM.2023-03-31/clinical.tsv", header=TRUE)
clinical_exposure = read.delim("~/Documentos/GitHub/Extra-o_Work/clinical.project-TCGA-GBM.2023-03-31/exposure.tsv", header=TRUE)
```

#2.2 Import dos Dados Project

```{r}

project_aliquot = read.delim("~/Documentos/GitHub/Extra-o_Work/biospecimen.project-TCGA-GBM.2023-03-31/aliquot.tsv", header=TRUE)
project_analyte = read.delim("~/Documentos/GitHub/Extra-o_Work/biospecimen.project-TCGA-GBM.2023-03-31/analyte.tsv", header=TRUE)
project_portion = read.delim("~/Documentos/GitHub/Extra-o_Work/biospecimen.project-TCGA-GBM.2023-03-31/portion.tsv", header=TRUE)
project_sample = read.delim("~/Documentos/GitHub/Extra-o_Work/biospecimen.project-TCGA-GBM.2023-03-31/sample.tsv", header=TRUE)
project_slide = read.delim("~/Documentos/GitHub/Extra-o_Work/biospecimen.project-TCGA-GBM.2023-03-31/slide.tsv", header=TRUE)

```

#2.3  Import Expression Data

```{r}
expression_data = read.delim("~/Documentos/GitHub/Extra-o_Work/gdc_download_20230331_112219.521695/ddb16b8d-9ad8-4c66-a986-513d3507b26d/1076483a-e462-47e5-a47a-ca9544548dff.rna_seq.augmented_star_gene_counts.tsv", comment.char="#")
```


# Auxiliar Function
```{r}

treatment_unique_colums = function(df){
  cols_delete = sapply(df, function(x) length(unique(x))) == 1
  df = df[, !cols_delete]
}
```


# Pré Tratamento
Apagar colunas com apenas 1 valores unico 

```{r}

treatment_unique_colums(clinical_clinical)
treatment_unique_colums(clinical_exposure)
treatment_unique_colums(project_aliquot)
treatment_unique_colums(project_analyte)
treatment_unique_colums(project_clinical)
treatment_unique_colums(project_portion)
treatment_unique_colums(project_slide)


```
# tentativa dna seq tirar dados


 
 
```{r}
library(TCGAbiolinks)
library(SummarizedExperiment)


gdcprojects = getGDCprojects()
query = GDCquery(project = "TCGA-GBM", data.category = "Transcriptome Profiling",experimental.strategy = "RNA-Seq", access = "open")
output = getResults(query)

GDCdownload(query)
```

```{r}

data = GDCprepare(query, summarizedExperiment = TRUE)

data_mat = assay(data, "unstranded" )
data_mat

```


